image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s maven/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=maven/repository"

cache:
  paths:
    - maven/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master